/* Amalgamation file: compiles all SILK sources (common + float) as
 * a single translation unit for the Go/Cgo build.
 */

/* ── SILK common sources ───────────────────────────────────────────── */

#include "libopus/silk/CNG.c"
#include "libopus/silk/code_signs.c"
#include "libopus/silk/init_decoder.c"
#include "libopus/silk/decode_core.c"
#include "libopus/silk/decode_frame.c"
#include "libopus/silk/decode_parameters.c"
#include "libopus/silk/decode_indices.c"
#include "libopus/silk/decode_pulses.c"
#include "libopus/silk/decoder_set_fs.c"
#include "libopus/silk/dec_API.c"
#include "libopus/silk/enc_API.c"
#include "libopus/silk/encode_indices.c"
#include "libopus/silk/encode_pulses.c"
#include "libopus/silk/gain_quant.c"
#include "libopus/silk/interpolate.c"
#include "libopus/silk/LP_variable_cutoff.c"
#include "libopus/silk/NLSF_decode.c"
#include "libopus/silk/NSQ.c"
#include "libopus/silk/NSQ_del_dec.c"
#include "libopus/silk/PLC.c"
#include "libopus/silk/shell_coder.c"
#include "libopus/silk/tables_gain.c"
#include "libopus/silk/tables_LTP.c"
#include "libopus/silk/tables_NLSF_CB_NB_MB.c"
#include "libopus/silk/tables_NLSF_CB_WB.c"
#include "libopus/silk/tables_other.c"
#include "libopus/silk/tables_pitch_lag.c"
#include "libopus/silk/tables_pulses_per_block.c"
#include "libopus/silk/VAD.c"
#include "libopus/silk/control_audio_bandwidth.c"
#include "libopus/silk/quant_LTP_gains.c"
#include "libopus/silk/VQ_WMat_EC.c"
#include "libopus/silk/HP_variable_cutoff.c"
#include "libopus/silk/NLSF_encode.c"
#include "libopus/silk/NLSF_VQ.c"
#include "libopus/silk/NLSF_unpack.c"
#include "libopus/silk/NLSF_del_dec_quant.c"
#include "libopus/silk/process_NLSFs.c"
#include "libopus/silk/stereo_LR_to_MS.c"
#include "libopus/silk/stereo_MS_to_LR.c"
#include "libopus/silk/check_control_input.c"
#include "libopus/silk/control_SNR.c"
#include "libopus/silk/init_encoder.c"
#include "libopus/silk/control_codec.c"
#include "libopus/silk/A2NLSF.c"
#include "libopus/silk/ana_filt_bank_1.c"
#include "libopus/silk/biquad_alt.c"
#include "libopus/silk/bwexpander_32.c"
#include "libopus/silk/bwexpander.c"
#include "libopus/silk/debug.c"
#include "libopus/silk/decode_pitch.c"
#include "libopus/silk/inner_prod_aligned.c"
#include "libopus/silk/lin2log.c"
#include "libopus/silk/log2lin.c"
#include "libopus/silk/LPC_analysis_filter.c"
#include "libopus/silk/LPC_inv_pred_gain.c"
#undef QA /* Defined differently in LPC_inv_pred_gain.c (24) and NLSF2A.c (16). */
#include "libopus/silk/table_LSF_cos.c"
#include "libopus/silk/NLSF2A.c"
#include "libopus/silk/NLSF_stabilize.c"
#include "libopus/silk/NLSF_VQ_weights_laroia.c"
#include "libopus/silk/pitch_est_tables.c"
#include "libopus/silk/resampler.c"
#include "libopus/silk/resampler_down2_3.c"
#include "libopus/silk/resampler_down2.c"
#include "libopus/silk/resampler_private_AR2.c"
#include "libopus/silk/resampler_private_down_FIR.c"
#include "libopus/silk/resampler_private_IIR_FIR.c"
#include "libopus/silk/resampler_private_up2_HQ.c"
#include "libopus/silk/resampler_rom.c"
#include "libopus/silk/sigm_Q15.c"
#include "libopus/silk/sort.c"
#include "libopus/silk/sum_sqr_shift.c"
#include "libopus/silk/stereo_decode_pred.c"
#include "libopus/silk/stereo_encode_pred.c"
#include "libopus/silk/stereo_find_predictor.c"
#include "libopus/silk/stereo_quant_pred.c"
#include "libopus/silk/LPC_fit.c"

/* ── SILK floating-point sources ───────────────────────────────────── */

#include "libopus/silk/float/apply_sine_window_FLP.c"
#include "libopus/silk/float/corrMatrix_FLP.c"
#include "libopus/silk/float/encode_frame_FLP.c"
#include "libopus/silk/float/find_LPC_FLP.c"
#include "libopus/silk/float/find_LTP_FLP.c"
#include "libopus/silk/float/find_pitch_lags_FLP.c"
#include "libopus/silk/float/find_pred_coefs_FLP.c"
#include "libopus/silk/float/LPC_analysis_filter_FLP.c"
#include "libopus/silk/float/LTP_analysis_filter_FLP.c"
#include "libopus/silk/float/LTP_scale_ctrl_FLP.c"
#include "libopus/silk/float/noise_shape_analysis_FLP.c"
#include "libopus/silk/float/process_gains_FLP.c"
#include "libopus/silk/float/regularize_correlations_FLP.c"
#include "libopus/silk/float/residual_energy_FLP.c"
#include "libopus/silk/float/warped_autocorrelation_FLP.c"
#include "libopus/silk/float/wrappers_FLP.c"
#include "libopus/silk/float/autocorrelation_FLP.c"
#include "libopus/silk/float/burg_modified_FLP.c"
#include "libopus/silk/float/bwexpander_FLP.c"
#include "libopus/silk/float/energy_FLP.c"
#include "libopus/silk/float/inner_product_FLP.c"
#include "libopus/silk/float/k2a_FLP.c"
#include "libopus/silk/float/LPC_inv_pred_gain_FLP.c"
#include "libopus/silk/float/pitch_analysis_core_FLP.c"
#include "libopus/silk/float/scale_copy_vector_FLP.c"
#include "libopus/silk/float/scale_vector_FLP.c"
#include "libopus/silk/float/schur_FLP.c"
#include "libopus/silk/float/sort_FLP.c"

/* NEON intrinsic sources. Included only under OPUS_PRODUCTION_C
 * (Go build tag `opus_production_c`). Default scalar oracle build
 * omits them — see libopus/config.h for the rationale.
 *
 * Note: the SILK x86 directory only contains fixed-point headers;
 * the float-mode SILK path has no SSE intrinsic sources upstream. */
#ifdef OPUS_PRODUCTION_C
#  if defined(__aarch64__) || defined(_M_ARM64)
/* arm_silk_map.c is the RTCD dispatch table; skipped because we use
 * OPUS_ARM_PRESUME_NEON_INTR (static dispatch, no table needed). It
 * also #includes main_FIX.h which is fixed-point-only. */
#    include "libopus/silk/arm/LPC_inv_pred_gain_neon_intr.c"
#    include "libopus/silk/arm/biquad_alt_neon_intr.c"
#    include "libopus/silk/arm/NSQ_neon.c"
#    include "libopus/silk/arm/NSQ_del_dec_neon_intr.c"
#  endif
#endif
