package vad

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/daniel-sullivan/go-mediatoolkit/vad/internal/goldensignals"
	"github.com/daniel-sullivan/go-mediatoolkit/vad/internal/silero"
)

// TestSileroGolden is the default-CI Silero parity gate: it pins the
// pure-Go port against oracle probabilities produced by onnxruntime
// (testdata/silero_golden.json, generated by
// internal/parity_tests/silero_ort/gen) at the same per-window 1e-4
// bound the opt-in ORT slice enforces — see that slice's package doc
// for the tolerance justification. It needs no onnxruntime, so it
// runs everywhere, and the silero-parity workflow re-runs the oracle
// and fails if the committed values drift beyond the same tolerance
// (gen -verify) — the goldens cannot drift from the oracle.
func TestSileroGolden(t *testing.T) {
	golden, err := goldensignals.LoadGolden("testdata/silero_golden.json")
	require.NoError(t, err)
	require.Equal(t, goldensignals.SampleRate, golden.SampleRate)
	require.Equal(t, goldensignals.WindowSize, golden.WindowSize)
	require.Equal(t, silero.WindowSize, golden.WindowSize)
	assert.NotEmpty(t, golden.OnnxRuntimeVersion)

	model, err := silero.New()
	require.NoError(t, err)

	const tolerance = 1e-4
	signals := goldensignals.Signals()
	require.Len(t, golden.Probabilities, len(signals), "golden file signal count")

	overallMax := 0.0
	for _, sig := range signals {
		want, ok := golden.Probabilities[sig.Name]
		require.True(t, ok, "golden file missing signal %q — regenerate with golden:gen", sig.Name)
		require.Len(t, want, len(sig.Samples)/silero.WindowSize,
			"%s window count — regenerate with golden:gen", sig.Name)

		model.Reset()
		sigMax := 0.0
		for w := range want {
			p, err := model.Process(sig.Samples[w*silero.WindowSize : (w+1)*silero.WindowSize])
			require.NoError(t, err)
			d := float64(p) - want[w]
			if d < 0 {
				d = -d
			}
			if d > sigMax {
				sigMax = d
			}
			if d > tolerance {
				t.Errorf("%s window %d: p_go=%.9f p_golden=%.9f |Δ|=%.3e > %g",
					sig.Name, w, p, want[w], d, tolerance)
			}
		}
		t.Logf("%s: %d windows, max |Δp| = %.3e", sig.Name, len(want), sigMax)
		if sigMax > overallMax {
			overallMax = sigMax
		}
	}
	t.Logf("overall max |Δp| = %.3e (tolerance %g)", overallMax, tolerance)
}
