// Write example: generate a sine sweep and write it to a WAV file with
// full INFO and broadcast-WAV (bext) metadata.
//
// Usage: write <output.wav>
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/daniel-sullivan/go-mediatoolkit/codec/pcm"
	"github.com/daniel-sullivan/go-mediatoolkit/consts"
	"github.com/daniel-sullivan/go-mediatoolkit/containers"
	"github.com/daniel-sullivan/go-mediatoolkit/containers/wav"
	"github.com/daniel-sullivan/go-mediatoolkit/generators"
	"github.com/daniel-sullivan/go-mediatoolkit/mutations"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatalf("usage: %s <output.wav>", os.Args[0])
	}

	const (
		sampleRate = consts.SampleRate48000
		channels   = 1
		duration   = 2 * time.Second
	)
	samples := generators.SineSweep(200, 4000, duration, sampleRate)

	f, err := os.Create(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	h := wav.Header{
		SampleRate:   sampleRate,
		Channels:     channels,
		SampleFormat: mutations.FormatInt24,
		Tags: containers.StandardTags{
			Title:   new("200 Hz -> 4 kHz sweep"),
			Artist:  new("go-mediatoolkit"),
			Date:    new("2026-04-22"),
			Genre:   new("test signal"),
			Comment: new("Generated by containers/wav/examples/write"),
			Encoder: new("github.com/daniel-sullivan/go-mediatoolkit/containers/wav"),
		},
		Extra: wav.Extras{
			Bext: &wav.BroadcastExt{
				Description:     "sine sweep test tone",
				Originator:      "go-mediatoolkit",
				OriginationDate: "2026-04-22",
				OriginationTime: "00:00:00",
				Version:         1,
				CodingHistory:   "A=PCM,F=48000,W=24,M=mono,T=go-mediatoolkit",
			},
		},
	}

	w, err := wav.NewWriter(f, h)
	if err != nil {
		log.Fatal(err)
	}
	enc, err := pcm.NewEncoder(w.Data(), h.SampleRate, h.Channels, h.SampleFormat)
	if err != nil {
		log.Fatal(err)
	}

	if _, err := enc.Write(samples); err != nil {
		log.Fatal(err)
	}
	if err := enc.Close(); err != nil {
		log.Fatal(err)
	}
	if err := w.Close(); err != nil {
		log.Fatal(err)
	}

	stat, _ := f.Stat()
	fmt.Printf("wrote %s: %d samples, %d bytes\n", os.Args[1], len(samples.Data), stat.Size())
}
