//go:build ignore

// gen_coeffs downloads sinc filter coefficient tables from the libsamplerate
// repository and generates Go source files.
//
// Usage: go run gen_coeffs.go
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
)

type coeffFile struct {
	url     string
	varName string
	outFile string
}

var files = []coeffFile{
	{
		url:     "https://raw.githubusercontent.com/libsndfile/libsamplerate/master/src/fastest_coeffs.h",
		varName: "fastestCoeffs",
		outFile: "coeffs_fastest.go",
	},
	{
		url:     "https://raw.githubusercontent.com/libsndfile/libsamplerate/master/src/mid_qual_coeffs.h",
		varName: "midQualCoeffs",
		outFile: "coeffs_midqual.go",
	},
	{
		url:     "https://raw.githubusercontent.com/libsndfile/libsamplerate/master/src/high_qual_coeffs.h",
		varName: "highQualCoeffs",
		outFile: "coeffs_highqual.go",
	},
}

func main() {
	for _, f := range files {
		fmt.Printf("Fetching %s...\n", f.url)
		inc, coeffs, err := fetchAndParse(f.url)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error processing %s: %v\n", f.url, err)
			os.Exit(1)
		}
		fmt.Printf("  increment=%d, coefficients=%d\n", inc, len(coeffs))

		if err := writeGoFile(f.outFile, f.varName, inc, coeffs); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", f.outFile, err)
			os.Exit(1)
		}
		fmt.Printf("  Wrote %s\n", f.outFile)
	}
}

func fetchAndParse(url string) (int, []string, error) {
	resp, err := http.Get(url)
	if err != nil {
		return 0, nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, nil, err
	}

	return parseCoeffs(string(body))
}

func parseCoeffs(src string) (int, []string, error) {
	// Extract increment from the comment block (e.g., "increment        : 128").
	incRe := regexp.MustCompile(`increment\s*:\s*(\d+)`)
	m := incRe.FindStringSubmatch(src)
	if m == nil {
		return 0, nil, fmt.Errorf("could not find increment value")
	}
	var inc int
	fmt.Sscanf(m[1], "%d", &inc)

	// Find the coefficient data between the inner braces of the initialization.
	// The structure is: } varname = { increment, { coeff0, coeff1, ... } } ;
	// Find the second '{' which starts the coefficient array.
	firstBrace := strings.Index(src, "=")
	if firstBrace < 0 {
		return 0, nil, fmt.Errorf("could not find initialization")
	}
	innerStart := strings.Index(src[firstBrace:], "\n{")
	if innerStart < 0 {
		return 0, nil, fmt.Errorf("could not find coefficient array start")
	}
	dataStart := firstBrace + innerStart

	// Extract all numbers (scientific notation and plain floats like 0.0).
	numRe := regexp.MustCompile(`[-+]?\d+\.\d+(?:[eE][-+]?\d+)?`)
	matches := numRe.FindAllString(src[dataStart:], -1)

	if len(matches) == 0 {
		return 0, nil, fmt.Errorf("no coefficients found")
	}

	return inc, matches, nil
}

func writeGoFile(filename, varName string, inc int, coeffs []string) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "// Code generated by gen_coeffs.go; DO NOT EDIT.\n\npackage resample\n\n")
	fmt.Fprintf(f, "var %s = coeffTable{\n\tincrement: %d,\n\tcoeffs: []float64{\n", varName, inc)

	// Write 4 coefficients per line for readability.
	for i, c := range coeffs {
		if i%4 == 0 {
			fmt.Fprintf(f, "\t\t")
		}
		fmt.Fprintf(f, "%s, ", c)
		if i%4 == 3 || i == len(coeffs)-1 {
			fmt.Fprintf(f, "\n")
		}
	}

	fmt.Fprintf(f, "\t},\n}\n")
	return nil
}
