package nativeopus

// Port of libopus/silk/define.h + errors.h + tuning_parameters.h +
// pitch_est_defines.h + resampler_structs.h + resampler_rom.h
// (declarations). Float-path only; ENABLE_QEXT disabled.

// ── errors.h ────────────────────────────────────────────────────────
const (
	SILK_NO_ERROR = 0

	SILK_ENC_INPUT_INVALID_NO_OF_SAMPLES      = -101
	SILK_ENC_FS_NOT_SUPPORTED                 = -102
	SILK_ENC_PACKET_SIZE_NOT_SUPPORTED        = -103
	SILK_ENC_PAYLOAD_BUF_TOO_SHORT            = -104
	SILK_ENC_INVALID_LOSS_RATE                = -105
	SILK_ENC_INVALID_COMPLEXITY_SETTING       = -106
	SILK_ENC_INVALID_INBAND_FEC_SETTING       = -107
	SILK_ENC_INVALID_DTX_SETTING              = -108
	SILK_ENC_INVALID_CBR_SETTING              = -109
	SILK_ENC_INTERNAL_ERROR                   = -110
	SILK_ENC_INVALID_NUMBER_OF_CHANNELS_ERROR = -111

	SILK_DEC_INVALID_SAMPLING_FREQUENCY = -200
	SILK_DEC_PAYLOAD_TOO_LARGE          = -201
	SILK_DEC_PAYLOAD_ERROR              = -202
	SILK_DEC_INVALID_FRAME_SIZE         = -203
)

// ── define.h ────────────────────────────────────────────────────────
const (
	ENCODER_NUM_CHANNELS = 2
	DECODER_NUM_CHANNELS = 2

	MAX_FRAMES_PER_PACKET = 3

	MIN_TARGET_RATE_BPS = 5000
	MAX_TARGET_RATE_BPS = 80000

	LBRR_NB_MIN_RATE_BPS = 12000
	LBRR_MB_MIN_RATE_BPS = 14000
	LBRR_WB_MIN_RATE_BPS = 16000

	NB_SPEECH_FRAMES_BEFORE_DTX = 10
	MAX_CONSECUTIVE_DTX         = 20
	DTX_ACTIVITY_THRESHOLD      = 0.1

	VAD_NO_DECISION = -1
	VAD_NO_ACTIVITY = 0
	VAD_ACTIVITY    = 1

	MAX_FS_KHZ     = 16
	MAX_API_FS_KHZ = 48

	TYPE_NO_VOICE_ACTIVITY = 0
	TYPE_UNVOICED          = 1
	TYPE_VOICED            = 2

	CODE_INDEPENDENTLY                = 0
	CODE_INDEPENDENTLY_NO_LTP_SCALING = 1
	CODE_CONDITIONALLY                = 2

	STEREO_QUANT_TAB_SIZE    = 16
	STEREO_QUANT_SUB_STEPS   = 5
	STEREO_INTERP_LEN_MS     = 8
	STEREO_RATIO_SMOOTH_COEF = 0.01

	PITCH_EST_MIN_LAG_MS = 2
	PITCH_EST_MAX_LAG_MS = 18

	MAX_NB_SUBFR = 4

	LTP_MEM_LENGTH_MS    = 20
	SUB_FRAME_LENGTH_MS  = 5
	MAX_SUB_FRAME_LENGTH = SUB_FRAME_LENGTH_MS * MAX_FS_KHZ
	MAX_FRAME_LENGTH_MS  = SUB_FRAME_LENGTH_MS * MAX_NB_SUBFR
	MAX_FRAME_LENGTH     = MAX_FRAME_LENGTH_MS * MAX_FS_KHZ

	LA_PITCH_MS  = 2
	LA_PITCH_MAX = LA_PITCH_MS * MAX_FS_KHZ

	MAX_FIND_PITCH_LPC_ORDER = 16

	FIND_PITCH_LPC_WIN_MS      = 20 + (LA_PITCH_MS << 1)
	FIND_PITCH_LPC_WIN_MS_2_SF = 10 + (LA_PITCH_MS << 1)
	FIND_PITCH_LPC_WIN_MAX     = FIND_PITCH_LPC_WIN_MS * MAX_FS_KHZ

	LA_SHAPE_MS  = 5
	LA_SHAPE_MAX = LA_SHAPE_MS * MAX_FS_KHZ

	SHAPE_LPC_WIN_MAX = 15 * MAX_FS_KHZ

	MIN_QGAIN_DB         = 2
	MAX_QGAIN_DB         = 88
	N_LEVELS_QGAIN       = 64
	MAX_DELTA_GAIN_QUANT = 36
	MIN_DELTA_GAIN_QUANT = -4

	OFFSET_VL_Q10  = 32
	OFFSET_VH_Q10  = 100
	OFFSET_UVL_Q10 = 100
	OFFSET_UVH_Q10 = 240

	QUANT_LEVEL_ADJUST_Q10 = 80

	MAX_LPC_STABILIZE_ITERATIONS          = 16
	MAX_PREDICTION_POWER_GAIN             = 1e4
	MAX_PREDICTION_POWER_GAIN_AFTER_RESET = 1e2

	MAX_LPC_ORDER = 16
	MIN_LPC_ORDER = 10

	LTP_ORDER = 5

	NB_LTP_CBKS = 3

	USE_HARM_SHAPING = 1

	MAX_SHAPE_LPC_ORDER = 24

	HARM_SHAPE_FIR_TAPS = 3

	MAX_DEL_DEC_STATES = 4

	LTP_BUF_LENGTH = 512
	LTP_MASK       = LTP_BUF_LENGTH - 1

	DECISION_DELAY = 40

	SHELL_CODEC_FRAME_LENGTH      = 16
	LOG2_SHELL_CODEC_FRAME_LENGTH = 4
	MAX_NB_SHELL_BLOCKS           = MAX_FRAME_LENGTH / SHELL_CODEC_FRAME_LENGTH

	N_RATE_LEVELS = 10

	SILK_MAX_PULSES = 16

	MAX_MATRIX_SIZE = MAX_LPC_ORDER

	NSQ_LPC_BUF_LENGTH = MAX_LPC_ORDER

	VAD_N_BANDS                 = 4
	VAD_INTERNAL_SUBFRAMES_LOG2 = 2
	VAD_INTERNAL_SUBFRAMES      = 1 << VAD_INTERNAL_SUBFRAMES_LOG2

	VAD_NOISE_LEVEL_SMOOTH_COEF_Q16 = 1024
	VAD_NOISE_LEVELS_BIAS           = 50

	VAD_NEGATIVE_OFFSET_Q5  = 128
	VAD_SNR_FACTOR_Q16      = 45000
	VAD_SNR_SMOOTH_COEF_Q18 = 4096

	LSF_COS_TAB_SZ_FIX = 128

	NLSF_W_Q                       = 2
	NLSF_VQ_MAX_VECTORS            = 32
	NLSF_QUANT_MAX_AMPLITUDE       = 4
	NLSF_QUANT_MAX_AMPLITUDE_EXT   = 10
	NLSF_QUANT_LEVEL_ADJ           = 0.1
	NLSF_QUANT_DEL_DEC_STATES_LOG2 = 2
	NLSF_QUANT_DEL_DEC_STATES      = 1 << NLSF_QUANT_DEL_DEC_STATES_LOG2

	TRANSITION_TIME_MS   = 5120
	TRANSITION_NB        = 3
	TRANSITION_NA        = 2
	TRANSITION_INT_NUM   = 5
	TRANSITION_FRAMES    = TRANSITION_TIME_MS / MAX_FRAME_LENGTH_MS
	TRANSITION_INT_STEPS = TRANSITION_FRAMES / (TRANSITION_INT_NUM - 1)

	BWE_AFTER_LOSS_Q16 = 63570

	CNG_BUF_MASK_MAX            = 255
	CNG_GAIN_SMTH_Q16           = 4634
	CNG_GAIN_SMTH_THRESHOLD_Q16 = 46396
	CNG_NLSF_SMTH_Q16           = 16348
)

// ── tuning_parameters.h ─────────────────────────────────────────────
const (
	BITRESERVOIR_DECAY_TIME_MS = 500

	FIND_PITCH_WHITE_NOISE_FRACTION = 1e-3
	FIND_PITCH_BANDWIDTH_EXPANSION  = 0.99

	FIND_LPC_COND_FAC   = 1e-5
	MAX_SUM_LOG_GAIN_DB = 250.0
	LTP_CORR_INV_MAX    = 0.03

	VARIABLE_HP_SMTH_COEF1     = 0.1
	VARIABLE_HP_SMTH_COEF2     = 0.015
	VARIABLE_HP_MAX_DELTA_FREQ = 0.4
	VARIABLE_HP_MIN_CUTOFF_HZ  = 60
	VARIABLE_HP_MAX_CUTOFF_HZ  = 100

	SPEECH_ACTIVITY_DTX_THRES  = 0.05
	LBRR_SPEECH_ACTIVITY_THRES = 0.3

	BG_SNR_DECR_dB = 2.0

	HARM_SNR_INCR_dB   = 2.0
	SPARSE_SNR_INCR_dB = 2.0

	ENERGY_VARIATION_THRESHOLD_QNT_OFFSET = 0.6

	WARPING_MULTIPLIER                        = 0.015
	SHAPE_WHITE_NOISE_FRACTION                = 3e-5
	BANDWIDTH_EXPANSION                       = 0.94
	HARMONIC_SHAPING                          = 0.3
	HIGH_RATE_OR_LOW_QUALITY_HARMONIC_SHAPING = 0.2
	HP_NOISE_COEF                             = 0.25
	HARM_HP_NOISE_COEF                        = 0.35
	INPUT_TILT                                = 0.05
	HIGH_RATE_INPUT_TILT                      = 0.1
	LOW_FREQ_SHAPING                          = 4.0
	LOW_QUALITY_LOW_FREQ_SHAPING_DECR         = 0.5
	SUBFR_SMTH_COEF                           = 0.4

	LAMBDA_OFFSET            = 1.2
	LAMBDA_SPEECH_ACT        = -0.2
	LAMBDA_DELAYED_DECISIONS = -0.05
	LAMBDA_INPUT_QUALITY     = -0.1
	LAMBDA_CODING_QUALITY    = -0.2
	LAMBDA_QUANT_OFFSET      = 0.8

	REDUCE_BITRATE_10_MS_BPS      = 2200
	MAX_BANDWIDTH_SWITCH_DELAY_MS = 5000
)
