//go:build cgo && rnnoise_strict

package tables

import (
	"math"
	"testing"

	"github.com/daniel-sullivan/go-mediatoolkit/denoise/internal/rnnoise"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// bitsEqf asserts two float32 values are identical by IEEE-754 bit
// pattern (so -0.0 vs +0.0 and NaN payloads are caught).
func bitsEqf(t *testing.T, ctx string, i int, c, g float32) {
	t.Helper()
	cb := math.Float32bits(c)
	gb := math.Float32bits(g)
	assert.Equalf(t, cb, gb, "%s[%d]: C=%v (0x%08x) Go=%v (0x%08x)", ctx, i, c, cb, g, gb)
}

// TestKFFTParams pins the static rnn_kfft scalar fields.
func TestKFFTParams(t *testing.T) {
	nfft, scale, shift, factors := rnnoise.KFFTParams()
	assert.Equal(t, cNFFT(), nfft, "nfft")
	bitsEqf(t, "scale", 0, cScale(), scale)
	assert.Equal(t, cShift(), shift, "shift")
	for i := 0; i < len(factors); i++ {
		assert.Equalf(t, cFactor(i), factors[i], "factors[%d]", i)
	}
}

// TestBitrevParity checks fft_bitrev[960] index-for-index.
func TestBitrevParity(t *testing.T) {
	g := rnnoise.FFTBitrev()
	require.Len(t, g, 960)
	for i := range g {
		assert.Equalf(t, cBitrev(i), g[i], "bitrev[%d]", i)
	}
}

// TestTwiddleParity checks the embedded fft_twiddles[960] against the C
// baked constants, bit-for-bit.
func TestTwiddleParity(t *testing.T) {
	gr := rnnoise.FFTTwiddleR()
	gi := rnnoise.FFTTwiddleI()
	require.Len(t, gr, 960)
	require.Len(t, gi, 960)
	for i := range gr {
		bitsEqf(t, "twiddle.r", i, cTwiddleR(i), gr[i])
		bitsEqf(t, "twiddle.i", i, cTwiddleI(i), gi[i])
	}
}

// TestHalfWindowParity checks rnn_half_window[480].
func TestHalfWindowParity(t *testing.T) {
	g := rnnoise.HalfWindow()
	require.Len(t, g, 480)
	for i := range g {
		bitsEqf(t, "half_window", i, cHalfWindow(i), g[i])
	}
}

// TestDctTableParity checks rnn_dct_table[1024].
func TestDctTableParity(t *testing.T) {
	g := rnnoise.DctTable()
	require.Len(t, g, 1024)
	for i := range g {
		bitsEqf(t, "dct_table", i, cDct(i), g[i])
	}
}

// TestTrigResolution answers the load-bearing question: does Go stdlib
// trig reproduce the twiddle bits the port relies on?
//
//	embedded-vs-baked:  the Go embedded table vs the C baked constants
//	                    (the actual shipping-parity guarantee).
//	live-libm-vs-baked: this machine's libm compute_twiddles vs the
//	                    baked constants (were the constants generated by
//	                    a bit-identical libm?).
//	go-trig-vs-live:    Go math.Cos/Sin vs this machine's libm for the
//	                    exact phases (the definitive Go-vs-libm answer).
//
// The port EMBEDS regardless (upstream ships the tables as constants);
// this test records the evidence and fails loudly only on the shipping
// guarantee (embedded-vs-baked). The two informational comparisons are
// reported via t.Log and a soft count so a divergence is visible
// without failing the gate.
func TestTrigResolution(t *testing.T) {
	const pi = 3.14159265358979323846264338327

	goTwiddle := func(i int) (r, im float32) {
		phase := (-2 * pi / float64(960)) * float64(i)
		return float32(math.Cos(phase)), float32(math.Sin(phase))
	}

	gr := rnnoise.FFTTwiddleR()
	gi := rnnoise.FFTTwiddleI()

	var liveVsBaked, goVsLive, goVsBaked int
	for i := 0; i < 960; i++ {
		br, bi := cTwiddleR(i), cTwiddleI(i)         // baked C constant
		lr, li := cLiveTwiddleR(i), cLiveTwiddleI(i) // this machine's libm
		xr, xi := goTwiddle(i)                       // Go stdlib trig

		if math.Float32bits(lr) != math.Float32bits(br) || math.Float32bits(li) != math.Float32bits(bi) {
			liveVsBaked++
		}
		if math.Float32bits(xr) != math.Float32bits(lr) || math.Float32bits(xi) != math.Float32bits(li) {
			goVsLive++
		}
		if math.Float32bits(xr) != math.Float32bits(br) || math.Float32bits(xi) != math.Float32bits(bi) {
			goVsBaked++
		}
		// Shipping guarantee: embedded table == baked C constants.
		bitsEqf(t, "embedded.r", i, br, gr[i])
		bitsEqf(t, "embedded.i", i, bi, gi[i])
	}

	t.Logf("TRIG RESOLUTION (960 twiddles):")
	t.Logf("  live-libm(this machine) vs baked-constant mismatches: %d", liveVsBaked)
	t.Logf("  Go-math.Cos/Sin        vs live-libm     mismatches: %d", goVsLive)
	t.Logf("  Go-math.Cos/Sin        vs baked-constant mismatches: %d", goVsBaked)
	if goVsBaked == 0 {
		t.Logf("  => Go stdlib trig reproduces the baked twiddles exactly; the port generates the 960-pt twiddles at init (kiss_fft.go computeTwiddles), bit-identical to the C table and with the correct signed zero at k=0.")
	} else {
		t.Logf("  => Go stdlib trig diverges from the baked twiddles on %d/960; embedding is MANDATORY (FLAC cosf-shim precedent).", goVsBaked)
	}
}
